name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: KNN Test
        run: |
          python -m unittest TestCases_knn.py
      - name: KMeans Test
        run: |
          python -m unittest TestCases_kmeans.py
      - name: My Labeling Test
        run: |
          python -m unittest my_labeling.py
